### ISSUE TITLE
Doesn't work under SBT 0.13.7

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [bmc/sbt-izpack#5]
When trying to use your plugin under SBT 0.13.7, I get this error:

	[info] Resolving org.clapper#sbt-izpack;0.3.4.2 ...
	[warn]  module not found: org.clapper#sbt-izpack;0.3.4.2
	[warn] ==== typesafe-ivy-releases: tried
	[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.clapper/sbt-izpack/scala_2.10/sbt_0.13/0.3.4.2/ivys/ivy.xml
	[warn] ==== sbt-plugin-releases: tried
	[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.clapper/sbt-izpack/scala_2.10/sbt_0.13/0.3.4.2/ivys/ivy.xml
	[warn] ==== local: tried
	[warn]   /home/d/.ivy2/local/org.clapper/sbt-izpack/scala_2.10/sbt_0.13/0.3.4.2/ivys/ivy.xml
	[warn] ==== public: tried
	[warn]   https://repo1.maven.org/maven2/org/clapper/sbt-izpack_2.10_0.13/0.3.4.2/sbt-izpack-0.3.4.2.pom
	[warn] ==== sbt-plugin-releases: tried
	[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/org.clapper/sbt-izpack/scala_2.10/sbt_0.13/0.3.4.2/ivys/ivy.xml
	[info] Resolving org.fusesource.jansi#jansi;1.4 ...
	[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
	[warn]  ::          UNRESOLVED DEPENDENCIES         ::
	[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
	[warn]  :: org.clapper#sbt-izpack;0.3.4.2: not found
	[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
	[warn] 
	[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
	[warn]          org.clapper:sbt-izpack:0.3.4.2 (sbtVersion=0.13, scalaVersion=2.10)

The contents of my `project/plugins.sbt` is the recommended one:

    addSbtPlugin("org.clapper" % "sbt-izpack" % "0.3.4.2")

    resolvers += Resolver.url(
		"sbt-plugin-releases",
		new URL("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/")
	)(Resolver.ivyStylePatterns)

**Comment by DavidPerezIngeniero** [comment]
It compiles under `SBT 0.13.7` with minor modifications.  :-)

Now, let's check if it works ok.

**Comment by bmc** [comment]
Well, cool. :-) If it works, send me a pull request. Thanks!

**Comment by bmc** [comment]
Fixed. Will publish and close tomorrow.

**Comment by bmc** [comment]
It was time to upgrade it anyway. It was using older APIs. I converted it to use the newer `AutoPlugin` interface.

**Comment by bmc** [comment]
Published as version 1.0.0.

**Comment by DavidPerezIngeniero** [comment]
When trying to use version 1.0.0, I'm having this error:

```
sbt.ResolveException: unresolved dependency: org.clapper#grizzled-scala_2.10;1.3: not found
```

Maybe some resolver must be configured or version `1.2` must be used.

**Comment by bmc** [comment]
I think I forgot to push `grizzled-scala` version 1.3 to the repo. I just did so. It'll take awhile to make its way to Maven Central, but you can always add the Bintray JCenter repo to your SBT configuration (in `plugins.sbt`, in this case):

```
repositories += "JCenter" at "http://jcenter.bintray.com/"
```

If that doesn't do it, try my direct Bintray repo:

```
repositories += "BMC Bintray" at "http://dl.bintray.com/bmc/maven"
```

**Comment by bmc** [comment]
BTW, if that works, please let me know, and I'll close this issue.

**Comment by DavidPerezIngeniero** [comment]
It works now.
Thanks once again.  :-)
